--
-- @lc app=leetcode id=571 lang=mysql
--
-- [571] Find Median Given Frequency of Numbers
--
-- https://leetcode.com/problems/find-median-given-frequency-of-numbers/description/
--
-- database
-- Hard (45.92%)
-- Total Accepted:    5.1K
-- Total Submissions: 11.2K
-- Testcase Example:  '{"headers": {"Numbers": ["Number", "Frequency"]}, "rows": {"Numbers": [[0, 7], [1, 1], [2, 3], [3, 1]]}}'
--
-- The Numbers table keeps the value of number and its frequency.
-- 
-- 
-- +----------+-------------+
-- |  Number  |  Frequency  |
-- +----------+-------------|
-- |  0       |  7          |
-- |  1       |  1          |
-- |  2       |  3          |
-- |  3       |  1          |
-- +----------+-------------+
-- 
-- 
-- In this table, the numbers are 0, 0, 0, 0, 0, 0, 0, 1, 2, 2, 2, 3, so the
-- median is (0 + 0) / 2 = 0.
-- 
-- 
-- +--------+
-- | median |
-- +--------|
-- | 0.0000 |
-- +--------+
-- 
-- 
-- Write a query to find the median of all numbers and name the result as
-- median.
-- 
--
# Write your MySQL query statement below

